### ISSUE TITLE
aos.listener.hooks

### ISSUE THREAD

**Issue by bizon1** [onemarshall/contao-aos#2]
Damit die Extension in Contao 4.6.x funktioniert muss die 
vendor/onemarshall/contao-aos/src/Resources/config/services.yml
wie folgt aussehen:
````
services:
  aos.listener.hooks:
    class: onemarshall\AosBundle\EventListener\HookListener
    public: true
````
